//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempsense.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Empresas()
        {
            this.tbl_Usuarios = new HashSet<tbl_Usuarios>();
            this.tbl_Sedes = new HashSet<tbl_Sedes>();
            this.tbl_ModulosXPerfil = new HashSet<tbl_ModulosXPerfil>();
        }
    
        public int IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Abr_Empresa { get; set; }
        public string Nit { get; set; }
        public string Correo { get; set; }
        public bool Activo { get; set; }
        public bool NotificaPorCorreo { get; set; }
        public bool NotificaPorMSM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Usuarios> tbl_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sedes> tbl_Sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ModulosXPerfil> tbl_ModulosXPerfil { get; set; }
    }
}
