//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempsense.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UltimasMedidas
    {
        public int MedidaID { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> DispositivoID { get; set; }
        public Nullable<System.DateTime> UltimaAlerta { get; set; }
    
        public virtual tbl_Dispositivos tbl_Dispositivos { get; set; }
    }
}
