//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempsense.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Umbrales
    {
        public int IdUmbral { get; set; }
        public decimal TemperaturaMin { get; set; }
        public decimal TemperaturaMax { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public int IdDispositivo { get; set; }
        public Nullable<decimal> ToleranciaMin { get; set; }
        public Nullable<decimal> ToleranciaMax { get; set; }
    
        public virtual tbl_Dispositivos tbl_Dispositivos { get; set; }
    }
}
