//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempsense.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bitacoras
    {
        public int IdBitacora { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public string Problema { get; set; }
        public string Solucion { get; set; }
        public int IdDispositivo { get; set; }
        public string Responsable { get; set; }
        public Nullable<System.DateTime> guardadodebitacora { get; set; }
    
        public virtual tbl_Dispositivos tbl_Dispositivos { get; set; }
        public virtual tbl_Dispositivos tbl_Dispositivos1 { get; set; }
    }
}
